services:
  - type: web
    name: kidmail-protector
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: kidmail-db
          property: connectionString

databases:
  - name: kidmail-db
    plan: free